Implements API's using ViewSets (V3)
Hamza-Chaudhary65/FinTrack pull request #10
Opened 2024-07-23 11:06 UTC by ChaudharyHamza65Chaudhary786

- Uses viewsets.viewset for class based API'S
- improves previous naming conventions
- indentation

2024-07-23 11:25 UTC, ZAINABFATIMA0 commented on fintrack/transactions/models.py
Why are we leaving this line empty ?

2024-07-23 11:30 UTC, ZAINABFATIMA0 commented on fintrack/transactions/transaction_helper.py
Why are we adding a prefix "transaction" in this helper file's name when we are already in transactions app.

2024-07-23 11:39 UTC, ZAINABFATIMA0 commented on fintrack/transactions/v3/views.py
> +                { "message": "Can not revert this transaction"},
There is an empty space immediately after the curly bracket

2024-07-23 11:39 UTC, ZAINABFATIMA0 commented on fintrack/transactions/v3/views.py
> +                { "message": "Reverted Successfully"}
There is an empty space immediately after the curly bracket

2024-07-23 11:41 UTC, ZAINABFATIMA0 commented on fintrack/transactions/v3/views.py
> +        transactions = Transaction.objects.filter(transaction_from_account__in=request.user.bank_accounts.all())
This line can be divided into two for better readability purpose

2024-07-23 12:09 UTC, ZAINABFATIMA0 approved these changes

2024-07-23 12:11 UTC, ChaudharyHamza65Chaudhary786 commented on fintrack/transactions/models.py
for readability.

2024-07-24 10:07 UTC, sheralim012 requested changes

2024-07-24 10:07 UTC, sheralim012 commented on fintrack/users/v3/views.py
> +    def create(self, request):
```suggestion
    permission_classes = []

        def create(self, request):
```

2024-07-24 11:06 UTC, sheralim012 approved these changes

2024-07-24 11:10 UTC, merged