Implements Model Admin to register models
Hamza-Chaudhary65/FinTrack pull request #11
Opened 2024-07-24 11:15 UTC by ChaudharyHamza65Chaudhary786

- Implements Model Admin to register models

2024-07-24 12:14 UTC, ZAINABFATIMA0 approved these changes

2024-07-24 12:19 UTC, sheralim012 requested changes
https://django-extensions.readthedocs.io/en/latest/admin_generator.html

2024-07-25 06:05 UTC, ZAINABFATIMA0 approved these changes

2024-07-25 06:47 UTC, sheralim012 requested changes

2024-07-25 06:47 UTC, sheralim012 commented on fintrack/users/admin.py
> +        'password',
do we need to show password?
don't just blindly follow things

2024-07-25 06:47 UTC, sheralim012 commented on fintrack/fintrack/settings.py
> +    'django_extensions'
update requirements.txt file

2024-07-25 06:47 UTC, sheralim012 commented on fintrack/banks/admin.py
> +    list_filter = ('bank',)
it's not recommended to include foreign keys into filter
reason is, when there is large amount of different objects in foreign key listing, it breaks the page

2024-07-25 08:09 UTC, sheralim012 approved these changes

2024-07-25 12:00 UTC, merged