Implements Forgot password functionality
Hamza-Chaudhary65/FinTrack pull request #16
Opened 2024-07-30 10:42 UTC by ChaudharyHamza65Chaudhary786

Implements Forgot password functionality

2024-07-30 13:54 UTC, ZAINABFATIMA0 approved these changes

2024-07-31 06:41 UTC, sheralim012 requested changes

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/models.py
> +class PasswordReset(models.Model):
shouldn't this be connected to user, as user model already has the email field?

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/models.py
> +    expiry_time= models.DateTimeField()
```suggestion
    expiry_time = models.DateTimeField()
```

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/models.py
> +            self.expiry_time = timezone.now() + timedelta(minutes=10)
you can do this via default value for the field itself

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/templates/reset_password_email.html
> +        <p><a href=" {{ reset_link}}" class="button">Reset Password</a></p>
```suggestion
        <p><a href=" {{ reset_link }}" class="button">Reset Password</a></p>
```

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/v4/views.py
> +        reset_url = f"{'http://127.0.0.1:8000/api/v4/user/password-reset/'}{token}"
I believe base URL should come from env variable

2024-07-31 06:41 UTC, sheralim012 commented on fintrack/users/v4/views.py
> +class ResetPasswordConfirm(CreateAPIView):
we aren't creating anything so why use createapiview?

2024-07-31 08:57 UTC, sheralim012 approved these changes

2024-07-31 09:23 UTC, merged